codecov:
  require_ci_to_pass: yes
  max_report_age: off

coverage:
  status:
    project:
      default:
        target: 50%   
    patch:
      default:
        target: 50%   

flags:
  frontend:
    paths:
      - src/
    carryforward: true
  backend:
    paths:
      - backend/
    carryforward: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
