coverage:
  status:
    project:
      default:
        target: 50%   
    patch:
      default:
        target: 50%   

flags:
  default:
    carryforward: true
    
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true

flags:
  frontend:
    carryforward: true
    paths:
      - src/
  backend:
    carryforward: true
    paths:
      - backend/