// src/mockData.js
export const mockListings = [
  {
    id: "1",
    title: "Calculus Textbook",
    description: "2nd edition, some notes in margins",
    specification: "",
    category: "Books",
    condition: "Good",
    price: 120,
    listingType: "For Sale",
    photos: [],
    sellerUID: "mock-user",
    timestamp: Date.now(),
  },
  {
    id: "2",
    title: "Laptop Charger",
    description: "Compatible with Dell and HP",
    specification: "",
    category: "Electronics",
    condition: "Like New",
    price: 300,
    listingType: "For Sale",
    photos: [],
    sellerUID: "mock-user",
    timestamp: Date.now(),
  },
  {
    id: "3",
    title: "Winter Jacket",
    description: "Warm, size M, lightly used",
    specification: "",
    category: "Clothing",
    condition: "Fair",
    price: 200,
    listingType: "For Trade",
    photos: [],
    sellerUID: "mock-user",
    timestamp: Date.now(),
  },
];